name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # github
  github: 

  # web related
  flutter_html: any
  url_strategy: ^0.2.0
  universal_html: ^2.0.4

  # http
  http: ^0.13.1

  # utils
  mailto: ^2.0.0
  flip_card: ^0.6.0
  url_launcher: ^6.1.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.1.0

  # state management
  provider: ^6.0.1

  # cache
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/work/
    - assets/photos/
    - assets/services/
    - assets/projects/

    - data.json

  fonts:
    - family: Agustina
      fonts:
        - asset: fonts/agustina/agustina.otf
    
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/montserrat.ttf
    
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic

